# примеры API-запросов

@port = 3000
@baseUrl = http://localhost:{{port}}

# получение тикетов
GET {{baseUrl}}/?method=allTickets

###

# получение тикета
GET {{baseUrl}}/?method=ticketById&id=2

###

# получение тикета
POST {{baseUrl}}/?method=createTicket
Content-Type: application/json

{
  "name": "asd",
  "description": "description123",
  "status": true
}

###